### ISSUE TITLE
Implement design flow for creating project and tasks

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/pshenmic-dev#22]
# Issue

We need a flow for administrators (for now just me), and allow them creating projects, creating tasks, and ability to buyout dev's claims

We need an UX interface mockup for these types of actions:
* Create project (name, description, url)
* Create task (title, description, url)
* Buyout people's claims

And we also would like to see a pages, where:
* User can see all projects
* User can see all tasks
* User can see all claims for given task

**Comment by blackmirrordesigner** [comment]
<img width="1728" alt="Current Claims" src="https://github.com/user-attachments/assets/9d3dd86b-062f-4860-b2f2-eaed115d8e6f">
<img width="1728" alt="Tasks-list - popup-step2" src="https://github.com/user-attachments/assets/9ec287b8-7057-4f3c-9d1c-705485574606">
<img width="1728" alt="Tasks-list - popup-requestfilled" src="https://github.com/user-attachments/assets/add5614c-f725-45bf-8af5-ed41d4cdddd0">
<img width="1728" alt="Create project - filled" src="https://github.com/user-attachments/assets/11cb08d4-e607-46d2-b570-522865953f94">
<img width="1728" alt="Create task - filled" src="https://github.com/user-attachments/assets/62333d65-8a96-436e-b3ca-9c0a21f06541">
<img width="1728" alt="Create task - select pokemon - hover" src="https://github.com/user-attachments/assets/3c3411f1-4c81-422a-a4e5-4fb8bae2a0d4">
<img width="1728" alt="Create task - select pokemon" src="https://github.com/user-attachments/assets/817196e7-afb5-496b-b4a9-5ac3673f35a7">
<img width="1728" alt="Create task - not filled-2" src="https://github.com/user-attachments/assets/8b75dda2-e048-4d27-8815-2a0f47b7f195">
<img width="1728" alt="Create task - not filled-1" src="https://github.com/user-attachments/assets/e4165fe8-cc0a-4e2f-9af0-e1e2bd724e4b">
<img width="1728" alt="Create task - not filled" src="https://github.com/user-attachments/assets/c4ec2290-9e2f-4ab6-9dcf-bd9f8af3ad55">
<img width="1728" alt="Create project - not filled" src="https://github.com/user-attachments/assets/ddd8256a-2b00-4383-9f53-f9d1f80bdf2e">
<img width="1728" alt="Tasks-list-2" src="https://github.com/user-attachments/assets/0664b11c-a8c2-4bd5-b9da-bafcc972ec0e">
<img width="1728" alt="Tasks-list-1" src="https://github.com/user-attachments/assets/fa701359-bf49-4536-8561-3d86e5888c33">
<img width="1728" alt="Tasks-list" src="https://github.com/user-attachments/assets/1a696877-f63d-4ec5-86f0-4a15bd8eae4a">
Figma link: https://www.figma.com/design/kd5jbDCEGhNKtImAwOprBf/Pshenmic---inside-pages?m=auto&t=qPwfFR1R7gOu6XWq-6

**Comment by blackmirrordesigner** [comment]
Updated pages for project and claims pages, both admin and simple user view:
<img width="1728" alt="Project list (admin)" src="https://github.com/user-attachments/assets/d4954df4-9331-4a59-8bea-c56513b1b6cc">
<img width="1728" alt="Project list (user)" src="https://github.com/user-attachments/assets/5001541c-bf96-4b1d-b354-2baaf6c525e3">
<img width="1728" alt="Current Claims - admin view" src="https://github.com/user-attachments/assets/b75c2a45-33ce-41e5-996b-03d59410c3ab">
<img width="1728" alt="Current Claims (user view)" src="https://github.com/user-attachments/assets/3595bfc7-2e0b-4260-91fb-10f9af2dbbe5">

Figma link for all the inside pages of Pshenmic website for this specific task: https://www.figma.com/design/kd5jbDCEGhNKtImAwOprBf/Pshenmic---inside-pages?node-id=0-1&t=1bI4BTpUFpMR5Ru1-1
