### ISSUE TITLE
Implement design flow for creating claims

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/pshenmic-dev#23]
# Issue

Implement design flow for developers who would like to claim there work and receive credits on his account

1) Developer opens up a task on the website
2) He sees a button "Claim"
3) He fills the form with deliverable url, and amount (in Dash Credits, but also shown in $) he would like claim for the task (optional)

Additionally, it should be possible change reward amount of the claim somewhere in the interface

**Comment by blackmirrordesigner** [comment]
https://www.figma.com/design/Z2X3FOq9IDrt0I5Dd4KJHO/Task-List?node-id=0-1&t=8B2SGixgoQeSZr3H-1
