### ISSUE TITLE
Design a Login \ Connect wallet flow

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/pshenmic-dev#24]
# Issue

For interaction with the website, we need a way to connect or authenticate via your wallet or seedphrase

**Comment by blackmirrordesigner** [comment]
<img width="1728" alt="Import Wallet - Private Key" src="https://github.com/user-attachments/assets/1904d83b-e64d-4e73-b7e6-da152a1249fc">
<img width="1728" alt="Import Wallet - Seed phrase - success" src="https://github.com/user-attachments/assets/cd8c1a70-c2c4-448b-917d-05517dc6f7fe">
<img width="1728" alt="Import Wallet - Seed phrase" src="https://github.com/user-attachments/assets/d7d7c9e6-7bba-49e9-b0b2-e5cff151477b">
https://www.figma.com/design/LrTXL2bPSnasoViIRW7TwN/Pshenmic---Import%2FConnect-wallet?m=auto&t=wrWGlfrzx25zoej0-6

**Comment by blackmirrordesigner** [comment]
<img width="781" alt="image" src="https://github.com/user-attachments/assets/fb817a70-e1bf-4ff2-b37b-f60218edda9d">
