### ISSUE TITLE
Design a comments / upvoting feature

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/pshenmic-dev#25]
# Issue
On the website, we would like to see comments & upvoting feature in the Projects, Tasks, Claims

**Comment by blackmirrordesigner** [comment]
<img width="1728" alt="One Project" src="https://github.com/user-attachments/assets/655e01bb-e574-4895-84aa-6ba6ae00fd67">
<img width="1728" alt="Project list (admin)" src="https://github.com/user-attachments/assets/2a1b4f03-6340-4637-8e79-d40ddd49dac9">
<img width="1731" alt="Tasks-list-comment" src="https://github.com/user-attachments/assets/e61e4d40-6fe6-4c3b-b33c-ff7b5eb3cbcd">
<img width="1731" alt="Tasks-list-voting" src="https://github.com/user-attachments/assets/c638c2b5-70bf-4f66-b55b-921e22b20e1f">
Figma link: https://www.figma.com/design/awDAQvXvD1ZY8yX0tQsIHw/Pshenmic---Upvoting-System?m=auto&t=wrWGlfrzx25zoej0-6
