### ISSUE TITLE
Preview of the new tasks and projects designs

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/pshenmic-dev#26]
# Issue

Platform Identity Authentication (Connect Wallet)
![image](https://github.com/user-attachments/assets/b9cf3fb9-8411-4829-9534-caf1bfd0222d)
![image](https://github.com/user-attachments/assets/65712428-39bd-4294-89d2-9cc16b55c34a)

The page with all projects list:
<img width="761" alt="image" src="https://github.com/user-attachments/assets/d4d2a026-952f-4f02-a65e-e84d8eec0613">
Specific project:
<img width="706" alt="image" src="https://github.com/user-attachments/assets/a1238ab1-a790-4666-8700-c94a1facbdec">

Task list:
<img width="645" alt="image" src="https://github.com/user-attachments/assets/fa698ecf-9dbb-449b-bb13-a3b02e6f6f7d">
Specific task:
<img width="644" alt="image" src="https://github.com/user-attachments/assets/6bb8ded0-bd34-4de6-8563-f6fd367f7759">
Claims list:
<img width="760" alt="image" src="https://github.com/user-attachments/assets/e4eb42cf-cc7f-4eab-8ccb-7475b11ae43b">
Make a claim:
<img width="763" alt="image" src="https://github.com/user-attachments/assets/52228fba-ce57-46b3-abe0-0b841988a74f">

**Comment by blackmirrordesigner** [comment]
![Uploading dash-proposal-bmd-pshenmic.png…]()

**Comment by blackmirrordesigner** [comment]
![dash-proposal-bmd-pshenmic](https://github.com/user-attachments/assets/6bee40b4-101d-48f9-9bbe-569b3c46c2b5)
